### ISSUE TITLE
client nightlies missing on the web pages

### ISSUE THREAD

**Issue by jnweiger** [owncloud/owncloud.org#1258]
https://owncloud.org/install/#testing-development has 

server
* testing and 
* nightlies (called daily) 

client
* testing
* testpilotcloud testing
* _no nighlies_

Please also add client nightlies  there.

**Comment by lefherz** [comment]
Testpilot is already there, I think, on the right. Should have a headline though.

**Comment by jnweiger** [comment]
You are right. I had mistaken the part on the right for the regular testing client, by looking at the link https://download.owncloud.com/desktop/testing/owncloudclient-2.3.3-rc2.tar.xz -- that are the sources of the regular client. the win mac linux binaries are indeed testpilotcloud binaries. 

Only nightlies are really missing.

**Comment by lefherz** [comment]
This actually has a reason: https://github.com/owncloud/owncloud.org/blob/master/strings.php#L37

There is an if-condition on https://github.com/owncloud/owncloud.org/blob/master/install-instructions.php#L356 which disables the nightly-builds if $VERSIONS_CLIENT_DESKTOP_TESTING is not empty. So atm they are not shown, because we offer RCs.

I added a headline for testpilots in https://github.com/owncloud/owncloud.org/pull/1259

**Comment by lefherz** [comment]
Look here if this fits your requirements: https://github.com/owncloud/owncloud.org/pull/1262

Something else is still missing on the page though - the android beta client. Discuss on https://github.com/owncloud/owncloud.org/pull/1261 whether it should be put on this page.

**Comment by Kawohl** [comment]
all aggregated to technical preview.
