### ISSUE TITLE
Clarification on Community vs Enterprise Editions

### ISSUE THREAD

**Issue by kelleybrooks** [owncloud/owncloud.org#266]
In an effort to clearly direct folks to the proper sites, I'd propose the following changes to the home page and download page.  Similar changes are being made on the .com site.

.org Homepage Edits
-Remove "enterprise Edition" from the top in orange
-Add two buttons to home page (top of the fold).  ownCloud for the Enterprise (links to .com homepage for now...will link elsewhere later) and ownCloud for Developers (link to Contribute page)
-Modify the "Company Support" header to "ownCloud for the Enterprise" and change summary beneath to read.  ownCloud Enterprise Edition was created with additional features and support to ensure your sensitive corporate data remains in your control.  See what <ownCloud edition> is best for you. 

Download page edits
-On https://owncloud.org/install/, add a link beneath "Looking for older versions?" that says "Want to use ownCloud for the Enterprise?  Find out more about <ownCloud Enterprise Edition>." And link to https://owncloud.com/products/enterprise/ in a new tab.

I will also request a landing page to be created in the .org template which will serve as a middle ground between the two sites.  I will add to this as we go.  Thanks.

**Comment by jospoortvliet** [comment]
With the recent improvements to org I think we've done a good job addressing this. Instead of dividing users between paying and non-paying, we outline the different support options and redirect users with professional deployments to .com (even if they have no intention to pay, there are free resources there and more coming).

owncloud.org/support gives an overview of what is available, so does the owncloud.org/faq page and the front page is adjusted too. I personally think this is a big step forward!

So, I'm closing this.
