### ISSUE TITLE
ownCloud client file filtering

### ISSUE THREAD

**Issue by labasus** [owncloud/owncloud.org#521]
Now we have only exclude rules to exclude some files from synchronizations.

But, where some situations then we need to sync Files//Folders with some more advanced logic like rsync have...

Sample:
1) sync files by spec. format from -  C:\DATA\file*.dbf (with subfolders) without original source path
2) sync directories -  C:\DATA\archive\ with original source path
3) sync multiply directories from client side with different inclusions/exclusions 
4) delete files after sync

**Comment by jospoortvliet** [comment]
Sorry, this is the bug tracker for the owncloud.org website, not for any part of ownCloud. Please, see the repositories on https://github.com/owncloud and file feature requests in the right one.

This seems a feature of the sync client. Note that 4 will not ever happen - that is not sync, that is backup. The other 3 - original source path or with original source path are again things I doubt will be implemented, the sync client should SYNC, not do backups. I suggest you use a backup tool for doing backups ;-)

And again - try to describe a scenario where this is helpful, rather than just describing a feature. Developing features costs time and once they are done they cost time to maintain, so only important and useful features are added - others are better left out.
