### ISSUE TITLE
Users managment

### ISSUE THREAD

**Issue by labasus** [owncloud/owncloud.org#522]
Adding for the new users are made in easy way.

1) There is no option to make add users with users details, like emails, notifications and etc, but it can be made after  from user logon (Personal button). What about admin, why these options are absent?

2) Also, where is no bulk users import/group changing/deleting

**Comment by jospoortvliet** [comment]
Sorry, this is the bug tracker for the owncloud.org website, not for any part of ownCloud. Please, see the repositories on https://github.com/owncloud and file feature requests in the right one.

I also suggest to try and describe your features more clearly. Features are only added if there is a clear use case - an example of a scenario where a feature is actually helpful, showing how currently something can not or only be done in a complex way but with the feature would be easily possible.

This feature probably belongs in owncloud/core.

For more complex user management most ownCloud users use LDAP, which has the featuares you describe under point two.

As to point 1, I don't see why an admin should be able to make these changes - it might be nice, but not important at all. A patch would perhaps be welcome if you feel like making this possible, but I can imagine that it is considered a unneeded feature. Can you describe a scenario where an admin MUST change these things, rather than the user? And where the admin can not, because it is a rare situation, work around it by logging in as the user for example?
