### ISSUE TITLE
  Older versions of the owncloud client for Linux

### ISSUE THREAD

**Issue by otobrzo** [owncloud/owncloud.org#837]
I need to use older version of the desktop client (2.0.2) and when I tried to download the client
here https://owncloud.org/changelog/desktop/
I realized that there is just the latest version for linux. For Windows and MAC you can download proper version.
This link (https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) is same for all versions listed in the previous link and even a 'Grab binary packages directly' link allow you to download latest version of the client (2.1). The repo contains only latest version.

**Comment by jospoortvliet** [comment]
We simply don't have that. What reason do you have to need/want the old client version? The latest should work with all supported versions of ownCloud and if you have an older version of ownCloud, honestly, you should upgrade as your ownCloud server has known and publicly documented security problems. For a home user, this shouldn't really be a big issue. If you're an enterprise user, I suggest to talk to owncloud.com about getting some help.

**Comment by otobrzo** [comment]
The reason why the older client is needed is described below:

'Dear CESNET ownCloud service users,

We would like to inform you that ownCloud client version 2.1.x can set
local data on synchronised computers into “read-only” mode. This setting
can be easily corrected locally, following synchronisation returns it to
read-only, though.

To prevent any inconvenience, we advise our users to keep client version to
2.0.2. Following steps ensure that you run compatible client version that
won't upgrade by itself:'

**Comment by danimo** [comment]
@otobrzo This is a feature: If files are shared read-only, that should be reflected in local file permissions. There have been some undesired side effects with this,  which are going to be fixed in 2.1.1. Unfortunately, copies on Windows are also read-only, but changing the state of the copy to read/write will be not be reversed.

**Comment by jospoortvliet** [comment]
@otobrzo in other words, 'just' get 2.1 or wait for 2.1.1 if you have problems, it should do what you'd expect (you can edit files you are allowed to edit and you won't be able to edit files you're not allowed to edit).

**Comment by awnz** [comment]
I also want to get 2.0.2 for Linux, because the loss of bandwidth control options in bug [4334](https://github.com/owncloud/core/issues/4334) on Ubuntu 14.04 means that the workaround to bug [9832](https://github.com/owncloud/core/issues/9832) that I was using up til now to stop synchronisation issues (including potential file corruption) can not be applied with 2.1.0+.

**Comment by greguric** [comment]
I would also like to have at least v2.3.2 because from version 2.3.3 I can't login to my server because something is wrong with LDAP (used to work perfectly)
Here's what I get:

> 
09-07 10:01:46:900 Mirall::Application::Application(int&, char**) Skipping update check 
09-07 10:01:46:906 SocketApi:  server started "/home/marko/.local/share/data/ownCloud/socket" 
09-07 10:01:47:023 Sys Info size:  1298 
09-07 10:01:47:241 !!! Mirall::CheckServerJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "status.php" 
09-07 10:01:47:473 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "7.0.4.2") ) ( "versionstring" ,  QVariant(QString, "7.0.4") ) )    0  Reply:  QNetworkReplyImpl(0x28e8ea0) 
09-07 10:01:47:474 ** Application: ownCloud found:   QUrl( "https://mojoblak.srce.hr/status.php" )   with version  "7.0.4" ( "7.0.4.2" ) 
09-07 10:01:47:519 !!! Mirall::PropfindJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "/" 
09-07 10:01:47:520 # checking for authentication settings. 
09-07 10:01:47:566 Quota request *not* successful, http result code is 200 "" 
09-07 10:02:18:901 !!! Mirall::CheckServerJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "status.php" 
09-07 10:02:18:997 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "7.0.4.2") ) ( "versionstring" ,  QVariant(QString, "7.0.4") ) )    0  Reply:  QNetworkReplyImpl(0x2893660) 
09-07 10:02:18:998 ** Application: ownCloud found:   QUrl( "https://mojoblak.srce.hr/status.php" )   with version  "7.0.4" ( "7.0.4.2" ) 
09-07 10:02:19:000 !!! Mirall::PropfindJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "/" 
09-07 10:02:19:001 # checking for authentication settings. 
09-07 10:02:19:077 Quota request *not* successful, http result code is 200 "" 
09-07 10:02:50:903 !!! Mirall::CheckServerJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "status.php" 
09-07 10:02:51:004 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "7.0.4.2") ) ( "versionstring" ,  QVariant(QString, "7.0.4") ) )    0  Reply:  QNetworkReplyImpl(0x2abbea0) 
09-07 10:02:51:005 ** Application: ownCloud found:   QUrl( "https://mojoblak.srce.hr/status.php" )   with version  "7.0.4" ( "7.0.4.2" ) 
09-07 10:02:51:007 !!! Mirall::PropfindJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "/" 
09-07 10:02:51:008 # checking for authentication settings. 
09-07 10:02:51:062 Quota request *not* successful, http result code is 200 "" 
09-07 10:03:22:900 !!! Mirall::CheckServerJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "status.php" 
09-07 10:03:22:990 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "7.0.4.2") ) ( "versionstring" ,  QVariant(QString, "7.0.4") ) )    0  Reply:  QNetworkReplyImpl(0x2c62ba0) 
09-07 10:03:22:991 ** Application: ownCloud found:   QUrl( "https://mojoblak.srce.hr/status.php" )   with version  "7.0.4" ( "7.0.4.2" ) 
09-07 10:03:22:993 !!! Mirall::PropfindJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "/" 
09-07 10:03:22:993 # checking for authentication settings. 
09-07 10:03:23:050 Quota request *not* successful, http result code is 200 "" 
09-07 10:03:54:900 !!! Mirall::CheckServerJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "status.php" 
09-07 10:03:55:009 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "7.0.4.2") ) ( "versionstring" ,  QVariant(QString, "7.0.4") ) )    0  Reply:  QNetworkReplyImpl(0x2c58b60) 
09-07 10:03:55:011 ** Application: ownCloud found:   QUrl( "https://mojoblak.srce.hr/status.php" )   with version  "7.0.4" ( "7.0.4.2" ) 
09-07 10:03:55:012 !!! Mirall::PropfindJob created for  QUrl( "https://mojoblak.srce.hr" )  querying "/" 
09-07 10:03:55:013 # checking for authentication settings. 
09-07 10:03:55:079 Quota request *not* successful, http result code is 200 ""
