### ISSUE TITLE
Modals not closable by clicking outside (above the modal)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#863]
For example on https://owncloud.org/install/#testing-development – you can only close the modal by clicking outside on the sides or below. But above (like on the navigation etc) it won’t close.

cc @jospoortvliet @tomneedham

**Comment by jospoortvliet** [comment]
Wouldn't know where to begin to fix this ;-)

**Comment by Prakharsvnit** [comment]
@jancborchardt @jospoortvliet I think it is due to fact that `<div>` of modal contains the part above it with class "PopupGetStarted" but this isn't same for sides and bottom of modal because it has class "mask" that's why modal doesn't closes when it is clicked on top but it closes when clicked on sides or below.
![screenshot from 2017-02-22 22-22-02](https://cloud.githubusercontent.com/assets/19989448/23222462/fd3e2470-f94d-11e6-910f-753b6f63e2eb.png)

**Comment by tomneedham** [comment]
hey @Prakharsvnit do you think you can make a pull request that fixes this?

**Comment by Prakharsvnit** [comment]
@tomneedham I'm currently working on this issue,will get back to you asap.

**Comment by jancborchardt** [comment]
@Prakharsvnit just as info because I’ll unsubscribe from this issue – both @jospoortvliet and me moved on to [Nextcloud](https://nextcloud.com). You are very welcome to contribute to our website too at https://github.com/nextcloud/nextcloud.com

**Comment by tomneedham** [comment]
@Prakharsvnit Did you make any progress with a PR for this?

**Comment by Kawohl** [comment]
@Prakharsvnit any update?

**Comment by Kawohl** [comment]
new site, no more modals
