### ISSUE TITLE
https://owncloud.org/support/ does not link to https://owncloud.help/

### ISSUE THREAD

**Issue by guruz** [owncloud/owncloud.org#883]

**Comment by aspdye** [comment]
D you really think it should? The /support/ page shows the various support options (Forum, Inc., ...).
And the owncloud.help shows "only" the KB. So I think their function is completely different :confused:

**Comment by aspdye** [comment]
I think the place where this resource should be listed is: https://owncloud.com/resources/ instead of the ownCloud.org/support - page :wink: I think the page is / and should be dedicated to the customers of ownCloud (and not the open source community). The owncloud.org/support - page does already point to https://owncloud.com/resources/ , so this is the place, where they (the ownCloud Inc.) should link to https://owncloud.help :wink: 

cc @karlitschek @MTRichards

**Comment by karlitschek** [comment]
@guruz because this is still in beta :-)

**Comment by jospoortvliet** [comment]
What frank said. We sure will link to it once this is actually a public, announced resource ;-)
